version: '3'
services:
  frontend:
    image: golang:1.21
    networks:
      - kong-api-gateway_kong-net
    restart: unless-stopped
    depends_on:
      - kafka
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app/frontend
    ports:
      - "8080:8080"
    command: go run .

  publisher:
    image: golang:1.21
    networks:
      - kong-api-gateway_kong-net
    restart: unless-stopped
    depends_on:
      - kafka
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app/publisher
    ports:
      - "8888:8888"
    command: go run .

  subscriber:
    image: golang:1.21
    networks:
      - kong-api-gateway_kong-net
    restart: unless-stopped
    depends_on:
      - kafka
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app/subscriber
    ports:
      - "8889:8889"
    command: go run .

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    networks:
      - kong-api-gateway_kong-net
    restart: unless-stopped
    logging:
      driver: none
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    networks:
      - kong-api-gateway_kong-net
    restart: unless-stopped
    depends_on:
      - zookeeper
    logging:
      driver: none
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

networks:
  kong-api-gateway_kong-net:
    external: true
    driver: bridge