_format_version: "3.0"
_transform: true

services:
- name: publisher
  url: http://publisher:8888
  plugins:
  - name: cors
    routes:
      - publish
  routes:
  - name: publish
    paths:
    - "/publisher"
    methods:
    - POST
- name: subscriber
  url: http://subscriber:8889
  paths: 
    - "/subscriber"
  plugins:
  - name: cors
    routes:
      - subscriber
  routes:
  - name: subscriber
    paths:
    - "/subscriber"
    methods:
    - GET
    - OPTIONS

plugins:
- name: cors
  config:
    origins:
    - http://localhost
    methods:
    - GET
    - POST
    headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - X-Auth-Token
    exposed_headers:
    - X-Auth-Token
    credentials: true
    max_age: 3600
    preflight_continue: false