_format_version: "3.0"
_transform: true

services:
  - name: publisher
    url: http://publisher:8888
    routes:
      - name: publish
        paths:
          - "/publisher"
        methods:
          - POST
          - OPTIONS

  - name: subscriber
    url: http://subscriber:8889
    routes:
      - name: subscriber
        paths:
          - "/subscriber"
        methods:
          - GET

  - name: namer
    url: http://namer:8890
    routes:
      - name: namer
        paths:
          - "/namer"
        methods:
          - GET

  - name: users
    url: http://users:8891
    routes:
      - name: users
        paths:
          - "/users"
        methods:
          - GET
          - POST
          - OPTIONS

plugins:
- name: cors
  config:
    origins:
      - "*"
    methods:
      - GET
      - POST
      - OPTIONS
    headers:
      - Accept
      - Accept-Version
      - Content-Length
      - Content-MD5
      - Content-Type
      - Date
      - X-Auth-Token
    exposed_headers:
      - X-Auth-Token
    credentials: true
    max_age: 3600
    preflight_continue: false